{
	'prompt': '1girl,upper body, black hair,Light pollution,pink light,blue light,night,,      ',
	'negative_prompt': '(unaestheticXLv31:0.6), negativeXL_D, deformed hands, long neck, long body, (bad hands), conjoined fingers, deformed fingers,badhandv4, EasyNegative,NG_DeepNegative_V1_75T, worst quality, low quality, normal quality, naked, nsfw, nipples, nude, lowres, bad anatomy, bad eyes, negative_hand-neg:11',
	'styles': [],
	'seed': -1,
	'subseed': -1,
	'subseed_strength': 0.0,
	'seed_resize_from_h': 0,
	'seed_resize_from_w': 0,
	'sampler_name': 'DPM++ 2M Karras',
	'batch_size': 1,
	'n_iter': 1,
	'steps': 40,
	'cfg_scale': 8.0,
	'width': 960,
	'height': 960,
	'restore_faces': False,
	'tiling': False,
	'do_not_save_samples': False,
	'do_not_save_grid': False,
	'eta': 1.0,
	'denoising_strength': 0.7,
	's_min_uncond': None,
	's_churn': 0.0,
	's_tmax': 0.0,
	's_tmin': 0.0,
	's_noise': 1.0,
	'override_settings': {},
	'override_settings_restore_afterwards': True,
	'refiner_checkpoint': None,
	'refiner_switch_at': None,
	'disable_extra_networks': False,
	'comments': None,
	'enable_hr': True,
	'firstphase_width': 0,
	'firstphase_height': 0,
	'hr_scale': 1.5,
	'hr_upscaler': '4x-UltraSharp',
	'hr_second_pass_steps': 20,
	'hr_resize_x': 0,
	'hr_resize_y': 0,
	'hr_checkpoint_name': None,
	'hr_sampler_name': None,
	'hr_prompt': '',
	'hr_negative_prompt': '',
	'sampler_index': 'Euler a',
	'script_name': None,
	'script_args': [],
	'send_images': True,
	'save_images': False,
	'alwayson_scripts': {
		'ControlNet': {
			'args': []
		}
	}
}